# Generated by Django 3.1.2 on 2020-10-29 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('created_on', models.DateField(verbose_name=datetime.datetime(2020, 10, 29, 0, 39, 48, 689943))),
            ],
        ),
    ]
