# Generated by Django 3.1.2 on 2020-10-29 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_on',
            field=models.DateField(verbose_name=datetime.datetime(2020, 10, 29, 0, 53, 34, 109709)),
        ),
    ]
